
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcd589ccd9294455f926ecc80da4711b2aaee57cbc06f1fe1e990d1cd211d58aceef679f1e867715ac1cd9ad0260083cbb1ee03a43a43516f501375fad9b94cb

test:
  secret_key_base: e55bb7b65c440a402b68dfb14ae0f5b94950d2c329a49fa75497b88fcac215ba5718fc4a62fef822c6492e1e01b3136d5d197da6afd0ac0273479724f6b08627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
